"""Fetch Georgia active alcohol licenses (DOR quarterly XLSX) -> georgia-stats.ts.

Standalone Python (XLSX needs openpyxl, outside the zero-dep Node pipeline — same
pattern as validation/make-xlsx.py). Run:  python data-pipeline/fetch-ga.py
Source:  https://dor.georgia.gov/active-alcohol-licenses  (statewide, quarterly XLSX)
Emits:   licensesignal/lib/georgia-stats.ts  (AUTO-GENERATED — do not hand-edit)

Georgia is expansion state #3 (after FL + TX). The file is a snapshot of ACTIVE
licenses with an "Account Commence Date" — licenses commenced in the last 12 months
are the "new venue" signal the feed is built on.
"""
import io
import json
import re
import urllib.request
from collections import Counter
from datetime import datetime, date
from pathlib import Path

import openpyxl

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT_TS = ROOT / "licensesignal" / "lib" / "georgia-stats.ts"
LANDING = "https://dor.georgia.gov/active-alcohol-licenses"
BASE = "https://dor.georgia.gov"
UA = "Mozilla/5.0 NewVenueData/1.0 (+https://newvenuedata.com)"


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=90) as r:
        return r.read() if binary else r.read().decode("utf-8", "replace")


def find_latest_xlsx():
    html = get(LANDING)
    links = re.findall(r'href="([^"]*alcohol-accounts-active-[^"]*?/download)"', html, re.I)
    if not links:
        raise SystemExit("No GA alcohol-licenses download link found on the landing page.")
    href = links[0]  # first link on the page = most recent quarter
    if href.startswith("/"):
        href = BASE + href
    m = re.search(r"active-([a-z]+)-(\d{4})", href, re.I)
    as_of = f"{m.group(1).title()} {m.group(2)}" if m else "latest"
    return href, as_of


def to_date(v):
    if isinstance(v, datetime):
        return v.date()
    if isinstance(v, date):
        return v
    try:
        return datetime.strptime(str(v)[:10], "%Y-%m-%d").date()
    except (ValueError, TypeError):
        return None


def main():
    url, as_of = find_latest_xlsx()
    wb = openpyxl.load_workbook(io.BytesIO(get(url, binary=True)), read_only=True, data_only=True)
    ws = wb.active
    rows = ws.iter_rows(values_only=True)
    header = [str(c).strip() if c is not None else "" for c in next(rows)]
    col_type = header.index("License Type") if "License Type" in header else None
    col_date = header.index("Account Commence Date") if "Account Commence Date" in header else None

    total = 0
    by_type = Counter()
    recent = 0
    today = date.today()
    for row in rows:
        total += 1
        if col_type is not None and col_type < len(row) and row[col_type]:
            by_type[str(row[col_type]).strip()] += 1
        if col_date is not None and col_date < len(row):
            d = to_date(row[col_date])
            if d and 0 <= (today - d).days <= 365:
                recent += 1

    top_types = [{"type": t, "count": n} for t, n in by_type.most_common(8)]
    OUT_TS.write_text(render_ts(as_of, total, len(by_type), recent, top_types), encoding="utf-8")
    print(f"wrote {OUT_TS.name}: {total} GA licenses, {len(by_type)} types, "
          f"{recent} commenced in last 12mo, as of {as_of}")


def render_ts(as_of, total, type_count, recent, top_types):
    types_json = json.dumps(top_types, indent=2)
    return (
        "// AUTO-GENERATED by data-pipeline/fetch-ga.py from the Georgia DOR \"Active\n"
        "// Alcohol Licenses\" quarterly XLSX (https://dor.georgia.gov/active-alcohol-licenses).\n"
        "// Real statewide aggregates for the /expansion/georgia preview. Do not hand-edit —\n"
        "// re-run the fetcher. See data-pipeline/SOURCES.md.\n"
        "export interface GaTypeStat { type: string; count: number }\n\n"
        f"export const GA_DATA_AS_OF = {json.dumps(as_of)}\n"
        "export const GA_SOURCE = 'Georgia Dept. of Revenue — Active Alcohol Licenses'\n"
        f"export const GA_TOTAL_LICENSES = {total}\n"
        f"export const GA_LICENSE_TYPE_COUNT = {type_count}\n"
        f"export const GA_RECENT_COMMENCEMENTS = {recent}\n"
        f"export const GA_TOP_TYPES: GaTypeStat[] = {types_json}\n"
    )


if __name__ == "__main__":
    main()
