export type FlRegion =
  | 'South'
  | 'Central'
  | 'North'
  | 'Southwest'
  | 'Panhandle'
  | 'Tampa Bay'

export interface FlCounty {
  slug: string
  name: string
  region: FlRegion
  seat: string
  monthlyFilings: number
  topCities: string[]
}

export const FL_COUNTIES: FlCounty[] = [
  {
    slug: 'miami-dade',
    name: 'Miami-Dade',
    region: 'South',
    seat: 'Miami',
    monthlyFilings: 412,
    topCities: ['Miami', 'Hialeah', 'Miami Beach', 'Coral Gables'],
  },
  {
    slug: 'broward',
    name: 'Broward',
    region: 'South',
    seat: 'Fort Lauderdale',
    monthlyFilings: 318,
    topCities: ['Fort Lauderdale', 'Hollywood', 'Pompano Beach', 'Coral Springs'],
  },
  {
    slug: 'orange',
    name: 'Orange',
    region: 'Central',
    seat: 'Orlando',
    monthlyFilings: 301,
    topCities: ['Orlando', 'Winter Park', 'Apopka', 'Ocoee'],
  },
  {
    slug: 'hillsborough',
    name: 'Hillsborough',
    region: 'Tampa Bay',
    seat: 'Tampa',
    monthlyFilings: 287,
    topCities: ['Tampa', 'Brandon', 'Riverview', 'Plant City'],
  },
  {
    slug: 'palm-beach',
    name: 'Palm Beach',
    region: 'South',
    seat: 'West Palm Beach',
    monthlyFilings: 264,
    topCities: ['West Palm Beach', 'Boca Raton', 'Boynton Beach', 'Delray Beach'],
  },
  {
    slug: 'duval',
    name: 'Duval',
    region: 'North',
    seat: 'Jacksonville',
    monthlyFilings: 241,
    topCities: ['Jacksonville', 'Jacksonville Beach', 'Atlantic Beach', 'Baldwin'],
  },
  {
    slug: 'pinellas',
    name: 'Pinellas',
    region: 'Tampa Bay',
    seat: 'Clearwater',
    monthlyFilings: 229,
    topCities: ['St. Petersburg', 'Clearwater', 'Largo', 'Dunedin'],
  },
  {
    slug: 'lee',
    name: 'Lee',
    region: 'Southwest',
    seat: 'Fort Myers',
    monthlyFilings: 168,
    topCities: ['Fort Myers', 'Cape Coral', 'Bonita Springs', 'Estero'],
  },
  {
    slug: 'polk',
    name: 'Polk',
    region: 'Central',
    seat: 'Bartow',
    monthlyFilings: 142,
    topCities: ['Lakeland', 'Winter Haven', 'Bartow', 'Haines City'],
  },
  {
    slug: 'brevard',
    name: 'Brevard',
    region: 'Central',
    seat: 'Titusville',
    monthlyFilings: 134,
    topCities: ['Melbourne', 'Palm Bay', 'Titusville', 'Cocoa Beach'],
  },
  {
    slug: 'sarasota',
    name: 'Sarasota',
    region: 'Southwest',
    seat: 'Sarasota',
    monthlyFilings: 127,
    topCities: ['Sarasota', 'Venice', 'North Port', 'Osprey'],
  },
  {
    slug: 'volusia',
    name: 'Volusia',
    region: 'Central',
    seat: 'DeLand',
    monthlyFilings: 121,
    topCities: ['Daytona Beach', 'Deltona', 'Port Orange', 'DeLand'],
  },
  {
    slug: 'collier',
    name: 'Collier',
    region: 'Southwest',
    seat: 'East Naples',
    monthlyFilings: 119,
    topCities: ['Naples', 'Marco Island', 'Immokalee', 'Golden Gate'],
  },
  {
    slug: 'seminole',
    name: 'Seminole',
    region: 'Central',
    seat: 'Sanford',
    monthlyFilings: 116,
    topCities: ['Sanford', 'Altamonte Springs', 'Lake Mary', 'Oviedo'],
  },
  {
    slug: 'pasco',
    name: 'Pasco',
    region: 'Tampa Bay',
    seat: 'Dade City',
    monthlyFilings: 109,
    topCities: ['New Port Richey', 'Wesley Chapel', 'Zephyrhills', 'Dade City'],
  },
  {
    slug: 'manatee',
    name: 'Manatee',
    region: 'Southwest',
    seat: 'Bradenton',
    monthlyFilings: 104,
    topCities: ['Bradenton', 'Palmetto', 'Lakewood Ranch', 'Anna Maria'],
  },
  {
    slug: 'alachua',
    name: 'Alachua',
    region: 'North',
    seat: 'Gainesville',
    monthlyFilings: 101,
    topCities: ['Gainesville', 'Alachua', 'Newberry', 'High Springs'],
  },
  {
    slug: 'leon',
    name: 'Leon',
    region: 'Panhandle',
    seat: 'Tallahassee',
    monthlyFilings: 98,
    topCities: ['Tallahassee', 'Midway', 'Woodville', 'Bradfordville'],
  },
  {
    slug: 'osceola',
    name: 'Osceola',
    region: 'Central',
    seat: 'Kissimmee',
    monthlyFilings: 97,
    topCities: ['Kissimmee', 'St. Cloud', 'Celebration', 'Poinciana'],
  },
  {
    slug: 'st-johns',
    name: 'St. Johns',
    region: 'North',
    seat: 'St. Augustine',
    monthlyFilings: 94,
    topCities: ['St. Augustine', 'St. Johns', 'Ponte Vedra Beach', 'Nocatee'],
  },
  {
    slug: 'escambia',
    name: 'Escambia',
    region: 'Panhandle',
    seat: 'Pensacola',
    monthlyFilings: 92,
    topCities: ['Pensacola', 'Brent', 'Ferry Pass', 'Gulf Breeze'],
  },
  {
    slug: 'marion',
    name: 'Marion',
    region: 'Central',
    seat: 'Ocala',
    monthlyFilings: 88,
    topCities: ['Ocala', 'Belleview', 'Dunnellon', 'Silver Springs'],
  },
  {
    slug: 'st-lucie',
    name: 'St. Lucie',
    region: 'South',
    seat: 'Fort Pierce',
    monthlyFilings: 86,
    topCities: ['Port St. Lucie', 'Fort Pierce', 'Tradition', 'St. Lucie West'],
  },
  {
    slug: 'okaloosa',
    name: 'Okaloosa',
    region: 'Panhandle',
    seat: 'Crestview',
    monthlyFilings: 81,
    topCities: ['Fort Walton Beach', 'Destin', 'Crestview', 'Niceville'],
  },
  {
    slug: 'lake',
    name: 'Lake',
    region: 'Central',
    seat: 'Tavares',
    monthlyFilings: 79,
    topCities: ['Clermont', 'Leesburg', 'Tavares', 'Mount Dora'],
  },
  {
    slug: 'bay',
    name: 'Bay',
    region: 'Panhandle',
    seat: 'Panama City',
    monthlyFilings: 76,
    topCities: ['Panama City', 'Panama City Beach', 'Lynn Haven', 'Callaway'],
  },
  {
    slug: 'charlotte',
    name: 'Charlotte',
    region: 'Southwest',
    seat: 'Punta Gorda',
    monthlyFilings: 71,
    topCities: ['Port Charlotte', 'Punta Gorda', 'Englewood', 'Rotonda West'],
  },
  {
    slug: 'martin',
    name: 'Martin',
    region: 'South',
    seat: 'Stuart',
    monthlyFilings: 67,
    topCities: ['Stuart', 'Palm City', 'Jensen Beach', 'Hobe Sound'],
  },
  {
    slug: 'clay',
    name: 'Clay',
    region: 'North',
    seat: 'Green Cove Springs',
    monthlyFilings: 64,
    topCities: ['Orange Park', 'Fleming Island', 'Middleburg', 'Green Cove Springs'],
  },
  {
    slug: 'hernando',
    name: 'Hernando',
    region: 'Tampa Bay',
    seat: 'Brooksville',
    monthlyFilings: 58,
    topCities: ['Spring Hill', 'Brooksville', 'Weeki Wachee', 'Hernando Beach'],
  },
  {
    slug: 'santa-rosa',
    name: 'Santa Rosa',
    region: 'Panhandle',
    seat: 'Milton',
    monthlyFilings: 54,
    topCities: ['Navarre', 'Milton', 'Pace', 'Gulf Breeze'],
  },
  {
    slug: 'indian-river',
    name: 'Indian River',
    region: 'South',
    seat: 'Vero Beach',
    monthlyFilings: 49,
    topCities: ['Vero Beach', 'Sebastian', 'Fellsmere', 'Wabasso'],
  },
  {
    slug: 'citrus',
    name: 'Citrus',
    region: 'Tampa Bay',
    seat: 'Inverness',
    monthlyFilings: 41,
    topCities: ['Inverness', 'Crystal River', 'Homosassa', 'Beverly Hills'],
  },
  {
    slug: 'flagler',
    name: 'Flagler',
    region: 'North',
    seat: 'Bunnell',
    monthlyFilings: 38,
    topCities: ['Palm Coast', 'Bunnell', 'Flagler Beach', 'Beverly Beach'],
  },
  {
    slug: 'sumter',
    name: 'Sumter',
    region: 'Central',
    seat: 'Bushnell',
    monthlyFilings: 37,
    topCities: ['The Villages', 'Wildwood', 'Bushnell', 'Coleman'],
  },
  {
    slug: 'nassau',
    name: 'Nassau',
    region: 'North',
    seat: 'Fernandina Beach',
    monthlyFilings: 33,
    topCities: ['Fernandina Beach', 'Yulee', 'Callahan', 'Hilliard'],
  },
  {
    slug: 'highlands',
    name: 'Highlands',
    region: 'Central',
    seat: 'Sebring',
    monthlyFilings: 29,
    topCities: ['Sebring', 'Avon Park', 'Lake Placid', 'Lorida'],
  },
  {
    slug: 'walton',
    name: 'Walton',
    region: 'Panhandle',
    seat: 'DeFuniak Springs',
    monthlyFilings: 31,
    topCities: ['Santa Rosa Beach', 'DeFuniak Springs', 'Miramar Beach', 'Freeport'],
  },
  {
    slug: 'putnam',
    name: 'Putnam',
    region: 'North',
    seat: 'Palatka',
    monthlyFilings: 24,
    topCities: ['Palatka', 'Interlachen', 'Crescent City', 'Welaka'],
  },
  {
    slug: 'monroe',
    name: 'Monroe',
    region: 'South',
    seat: 'Key West',
    monthlyFilings: 35,
    topCities: ['Key West', 'Key Largo', 'Marathon', 'Islamorada'],
  },
  {
    slug: 'columbia',
    name: 'Columbia',
    region: 'North',
    seat: 'Lake City',
    monthlyFilings: 23,
    topCities: ['Lake City', 'Fort White', 'Five Points', 'Watertown'],
  },
  {
    slug: 'okeechobee',
    name: 'Okeechobee',
    region: 'South',
    seat: 'Okeechobee',
    monthlyFilings: 18,
    topCities: ['Okeechobee', 'Buckhead Ridge', 'Taylor Creek', 'Cypress Quarters'],
  },
  {
    slug: 'gadsden',
    name: 'Gadsden',
    region: 'Panhandle',
    seat: 'Quincy',
    monthlyFilings: 16,
    topCities: ['Quincy', 'Chattahoochee', 'Havana', 'Midway'],
  },
  {
    slug: 'jackson',
    name: 'Jackson',
    region: 'Panhandle',
    seat: 'Marianna',
    monthlyFilings: 17,
    topCities: ['Marianna', 'Graceville', 'Sneads', 'Cottondale'],
  },
  {
    slug: 'wakulla',
    name: 'Wakulla',
    region: 'Panhandle',
    seat: 'Crawfordville',
    monthlyFilings: 14,
    topCities: ['Crawfordville', 'St. Marks', 'Panacea', 'Sopchoppy'],
  },
  {
    slug: 'levy',
    name: 'Levy',
    region: 'North',
    seat: 'Bronson',
    monthlyFilings: 13,
    topCities: ['Williston', 'Chiefland', 'Bronson', 'Cedar Key'],
  },
  {
    slug: 'desoto',
    name: 'DeSoto',
    region: 'Southwest',
    seat: 'Arcadia',
    monthlyFilings: 12,
    topCities: ['Arcadia', 'Nocatee', 'Fort Ogden', 'Lake Suzy'],
  },
  {
    slug: 'hendry',
    name: 'Hendry',
    region: 'Southwest',
    seat: 'LaBelle',
    monthlyFilings: 13,
    topCities: ['Clewiston', 'LaBelle', 'Felda', 'Port LaBelle'],
  },
  {
    slug: 'suwannee',
    name: 'Suwannee',
    region: 'North',
    seat: 'Live Oak',
    monthlyFilings: 12,
    topCities: ['Live Oak', 'Branford', 'Wellborn', 'McAlpin'],
  },
  {
    slug: 'baker',
    name: 'Baker',
    region: 'North',
    seat: 'Macclenny',
    monthlyFilings: 11,
    topCities: ['Macclenny', 'Glen St. Mary', 'Sanderson', 'Olustee'],
  },
  {
    slug: 'hardee',
    name: 'Hardee',
    region: 'Central',
    seat: 'Wauchula',
    monthlyFilings: 9,
    topCities: ['Wauchula', 'Bowling Green', 'Zolfo Springs', 'Ona'],
  },
  {
    slug: 'washington',
    name: 'Washington',
    region: 'Panhandle',
    seat: 'Chipley',
    monthlyFilings: 9,
    topCities: ['Chipley', 'Vernon', 'Wausau', 'Ebro'],
  },
  {
    slug: 'taylor',
    name: 'Taylor',
    region: 'North',
    seat: 'Perry',
    monthlyFilings: 9,
    topCities: ['Perry', 'Steinhatchee', 'Salem', 'Keaton Beach'],
  },
  {
    slug: 'bradford',
    name: 'Bradford',
    region: 'North',
    seat: 'Starke',
    monthlyFilings: 10,
    topCities: ['Starke', 'Lawtey', 'Hampton', 'Brooker'],
  },
  {
    slug: 'gilchrist',
    name: 'Gilchrist',
    region: 'North',
    seat: 'Trenton',
    monthlyFilings: 7,
    topCities: ['Trenton', 'Bell', 'Fanning Springs', 'Spring Ridge'],
  },
  {
    slug: 'holmes',
    name: 'Holmes',
    region: 'Panhandle',
    seat: 'Bonifay',
    monthlyFilings: 7,
    topCities: ['Bonifay', 'Westville', 'Noma', 'Ponce de Leon'],
  },
  {
    slug: 'gulf',
    name: 'Gulf',
    region: 'Panhandle',
    seat: 'Port St. Joe',
    monthlyFilings: 8,
    topCities: ['Port St. Joe', 'Wewahitchka', 'Mexico Beach', 'White City'],
  },
  {
    slug: 'dixie',
    name: 'Dixie',
    region: 'North',
    seat: 'Cross City',
    monthlyFilings: 6,
    topCities: ['Cross City', 'Horseshoe Beach', 'Suwannee', 'Old Town'],
  },
  {
    slug: 'union',
    name: 'Union',
    region: 'North',
    seat: 'Lake Butler',
    monthlyFilings: 5,
    topCities: ['Lake Butler', 'Raiford', 'Worthington Springs', 'Providence'],
  },
  {
    slug: 'madison',
    name: 'Madison',
    region: 'North',
    seat: 'Madison',
    monthlyFilings: 6,
    topCities: ['Madison', 'Greenville', 'Lee', 'Pinetta'],
  },
  {
    slug: 'jefferson',
    name: 'Jefferson',
    region: 'Panhandle',
    seat: 'Monticello',
    monthlyFilings: 6,
    topCities: ['Monticello', 'Lloyd', 'Wacissa', 'Aucilla'],
  },
  {
    slug: 'hamilton',
    name: 'Hamilton',
    region: 'North',
    seat: 'Jasper',
    monthlyFilings: 5,
    topCities: ['Jasper', 'Jennings', 'White Springs', 'Genoa'],
  },
  {
    slug: 'calhoun',
    name: 'Calhoun',
    region: 'Panhandle',
    seat: 'Blountstown',
    monthlyFilings: 5,
    topCities: ['Blountstown', 'Altha', 'Clarksville', 'Kinard'],
  },
  {
    slug: 'glades',
    name: 'Glades',
    region: 'Southwest',
    seat: 'Moore Haven',
    monthlyFilings: 4,
    topCities: ['Moore Haven', 'Buckhead Ridge', 'Palmdale', 'Ortona'],
  },
  {
    slug: 'franklin',
    name: 'Franklin',
    region: 'Panhandle',
    seat: 'Apalachicola',
    monthlyFilings: 7,
    topCities: ['Apalachicola', 'Carrabelle', 'Eastpoint', 'St. George Island'],
  },
  {
    slug: 'liberty',
    name: 'Liberty',
    region: 'Panhandle',
    seat: 'Bristol',
    monthlyFilings: 3,
    topCities: ['Bristol', 'Hosford', 'Sumatra', 'Telogia'],
  },
  {
    slug: 'lafayette',
    name: 'Lafayette',
    region: 'North',
    seat: 'Mayo',
    monthlyFilings: 3,
    topCities: ['Mayo', 'Day', 'Cooks Hammock', 'Hatchbend'],
  },
]

export function getCounty(slug: string): FlCounty | undefined {
  return FL_COUNTIES.find((county) => county.slug === slug)
}
