// AUTO-GENERATED by data-pipeline/fetch-ga.py from the Georgia DOR "Active
// Alcohol Licenses" quarterly XLSX (https://dor.georgia.gov/active-alcohol-licenses).
// Real statewide aggregates for the /expansion/georgia preview. Do not hand-edit —
// re-run the fetcher. See data-pipeline/SOURCES.md.
export interface GaTypeStat { type: string; count: number }

export const GA_DATA_AS_OF = "April 2026"
export const GA_SOURCE = 'Georgia Dept. of Revenue — Active Alcohol Licenses'
export const GA_TOTAL_LICENSES = 24895
export const GA_LICENSE_TYPE_COUNT = 15
export const GA_RECENT_COMMENCEMENTS = 2363
export const GA_TOP_TYPES: GaTypeStat[] = [
  {
    "type": "RETAIL",
    "count": 13242
  },
  {
    "type": "CONSUMPTION",
    "count": 7863
  },
  {
    "type": "SPCORDSHPR",
    "count": 1308
  },
  {
    "type": "BROKER",
    "count": 991
  },
  {
    "type": "FARMWINE",
    "count": 554
  },
  {
    "type": "DISTILLERY",
    "count": 251
  },
  {
    "type": "BREWERY",
    "count": 189
  },
  {
    "type": "WHOLESALER",
    "count": 145
  }
]
