// License records and aggregates are now REAL data, sourced from live Florida
// DBPR public records (AB&T + Hotels & Restaurants) and geocoded via the U.S.
// Census batch geocoder. See lib/real-data.ts (auto-generated by the
// data-pipeline) and data-pipeline/SOURCES.md for provenance and compliance.
// Pricing is product configuration and stays hand-authored here.
import type { LicenseRecord, DailyVolume, StatCardData, CountyVolume, PricingPlan, PricingFeature } from './types'
import {
  REAL_LICENSES,
  REAL_DAILY_VOLUME,
  REAL_STAT_CARDS,
  REAL_COUNTY_VOLUME,
} from './real-data'

export const MOCK_LICENSES: LicenseRecord[] = REAL_LICENSES
export const DAILY_VOLUME: DailyVolume[] = REAL_DAILY_VOLUME
export const STAT_CARDS: StatCardData[] = REAL_STAT_CARDS
export const COUNTY_VOLUME: CountyVolume[] = REAL_COUNTY_VOLUME

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 299,
    annualPrice: 249,
    description: 'Perfect for testing and single-market use cases.',
    features: [
      '1 Florida county',
      '5,000 API calls / month',
      'Webhook delivery',
      'CSV export (weekly)',
      'Email support',
      '30-day historical data',
    ],
    cta: 'Start Now',
    highlighted: false,
  },
  {
    id: 'pro',
    name: 'Professional',
    price: 999,
    annualPrice: 832,
    description: 'For teams running serious outbound or intelligence workflows.',
    features: [
      'All 67 Florida counties',
      '50,000 API calls / month',
      'Priority webhook delivery',
      'CSV export (daily)',
      'Contact enrichment',
      '2-year historical archive',
      'Slack support',
      'API sandbox environment',
    ],
    cta: 'Start Now',
    highlighted: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: null,
    annualPrice: null,
    description: 'Custom delivery, SLAs, and integrations for high-volume teams.',
    features: [
      'Unlimited API calls',
      '99.9% uptime SLA',
      'Raw data warehouse delivery',
      'Custom integrations',
      'Dedicated CSM',
      'Legal & compliance review',
      'Custom data contracts',
    ],
    cta: 'Talk to Sales',
    highlighted: false,
  },
]

export const PRICING_FEATURES: PricingFeature[] = [
  { name: 'Florida counties', starter: '1 county', pro: 'All 67', enterprise: 'All 67' },
  { name: 'API calls / month', starter: '5,000', pro: '50,000', enterprise: 'Unlimited' },
  { name: 'Webhook delivery', starter: true, pro: true, enterprise: true },
  { name: 'Priority webhooks', starter: false, pro: true, enterprise: true },
  { name: 'CSV export', starter: 'Weekly', pro: 'Daily', enterprise: 'Real-time' },
  { name: 'Historical archive', starter: '30 days', pro: '2 years', enterprise: 'Full archive' },
  { name: 'Contact enrichment', starter: false, pro: true, enterprise: true },
  { name: 'Ownership transfers', starter: false, pro: true, enterprise: true },
  { name: 'API sandbox', starter: false, pro: true, enterprise: true },
  { name: 'SLA guarantee', starter: false, pro: false, enterprise: '99.9%' },
  { name: 'Raw data delivery', starter: false, pro: false, enterprise: true },
  { name: 'Custom integrations', starter: false, pro: false, enterprise: true },
  { name: 'Dedicated CSM', starter: false, pro: false, enterprise: true },
  { name: 'Slack support', starter: false, pro: true, enterprise: true },
  { name: 'Support SLA', starter: '48h email', pro: '4h Slack', enterprise: '1h dedicated' },
]
