// License records and aggregates are now REAL data, sourced from live Florida
// DBPR public records (AB&T + Hotels & Restaurants) and geocoded via the U.S.
// Census batch geocoder. See lib/real-data.ts (auto-generated by the
// data-pipeline) and data-pipeline/SOURCES.md for provenance and compliance.
// Pricing is product configuration and stays hand-authored here.
import type { LicenseRecord, DailyVolume, StatCardData, CountyVolume, PricingPlan, PricingFeature } from './types'
import {
  REAL_LICENSES,
  REAL_DAILY_VOLUME,
  REAL_STAT_CARDS,
  REAL_COUNTY_VOLUME,
} from './real-data'

export const MOCK_LICENSES: LicenseRecord[] = REAL_LICENSES
export const DAILY_VOLUME: DailyVolume[] = REAL_DAILY_VOLUME
export const STAT_CARDS: StatCardData[] = REAL_STAT_CARDS
export const COUNTY_VOLUME: CountyVolume[] = REAL_COUNTY_VOLUME

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'County',
    price: 149,
    annualPrice: 124,
    description: 'One Florida county — ideal for a solo agent working a single territory.',
    features: [
      '1 Florida county',
      'Weekly new-license list (every Monday)',
      'New liquor + food-service filings',
      'Name, address, county, license type, filing date',
      'On-premises (bar / restaurant) filter',
      'CSV + Excel delivery',
      'Email support · cancel anytime',
    ],
    cta: 'Start Free Trial',
    highlighted: false,
  },
  {
    id: 'pro',
    name: 'South Florida',
    price: 299,
    annualPrice: 249,
    description: 'Broward, Miami-Dade & Palm Beach — the tri-county metro, all in one feed.',
    features: [
      'Everything in County, plus:',
      'All three South-FL counties',
      'Up to twice-weekly delivery',
      'API access (REST, key-authenticated)',
      '90-day filing history',
      'Priority email support',
    ],
    cta: 'Start Free Trial',
    highlighted: true,
  },
  {
    id: 'enterprise',
    name: 'Statewide · Feed & API',
    price: null,
    annualPrice: null,
    description: 'All 67 counties as a weekly feed or API — for agencies, wholesalers & MGAs. From $499/mo.',
    features: [
      'All 67 Florida counties',
      'Weekly data feed or REST API into your systems',
      'Custom delivery cadence',
      'Full filing history',
      'Volume & multi-seat pricing',
      'Dedicated support',
    ],
    cta: 'Talk to Sales',
    highlighted: false,
  },
]

export const PRICING_FEATURES: PricingFeature[] = [
  { name: 'Florida counties', starter: '1 county', pro: 'Tri-county', enterprise: 'All 67' },
  { name: 'Weekly new-license list', starter: true, pro: true, enterprise: true },
  { name: 'On-premises (bar / restaurant) filter', starter: true, pro: true, enterprise: true },
  { name: 'Delivery format', starter: 'CSV + Excel', pro: 'CSV + Excel + API', enterprise: 'Feed or API' },
  { name: 'Delivery cadence', starter: 'Weekly', pro: 'Up to 2×/week', enterprise: 'Custom' },
  { name: 'Filing history', starter: '30 days', pro: '90 days', enterprise: 'Full archive' },
  { name: 'API access', starter: false, pro: true, enterprise: true },
  { name: 'Custom integrations', starter: false, pro: false, enterprise: true },
  { name: 'Volume / multi-seat pricing', starter: false, pro: false, enterprise: true },
  { name: 'Support', starter: 'Email', pro: 'Priority email', enterprise: 'Dedicated' },
  { name: 'Cancel anytime', starter: true, pro: true, enterprise: true },
]
