// AUTO-GENERATED by data-pipeline/src/fetch-tabc.mjs from the Texas TABC public
// license file (data.texas.gov Socrata dataset 7hf9-qc9f, updated daily). Real
// statewide aggregates for the /expansion/texas preview. Sourced 2026-06-15.
// Do not hand-edit — re-run the fetcher. See data-pipeline/SOURCES.md.
export interface TxCountyStat { county: string; count: number }

export const TX_DATA_AS_OF = '2026-06-15'
export const TX_SOURCE = 'Texas Alcoholic Beverage Commission (TABC) — data.texas.gov'
export const TX_TOTAL_LICENSES = 124619
export const TX_LICENSE_TYPE_COUNT = 29
export const TX_TOP_COUNTIES: TxCountyStat[] = [
  {
    "county": "Harris",
    "count": 19730
  },
  {
    "county": "Dallas",
    "count": 9525
  },
  {
    "county": "Bexar",
    "count": 7401
  },
  {
    "county": "Tarrant",
    "count": 7153
  },
  {
    "county": "Travis",
    "count": 6223
  },
  {
    "county": "Hidalgo",
    "count": 3413
  },
  {
    "county": "Collin",
    "count": 3330
  },
  {
    "county": "El Paso",
    "count": 2928
  },
  {
    "county": "Denton",
    "count": 2509
  },
  {
    "county": "Montgomery",
    "count": 2434
  },
  {
    "county": "Fort Bend",
    "count": 2181
  }
]
