// Combine every acquired source into a unified BusinessSignal feed for the site:
// licenses + new-business registrations + commercial permits + retail food.
// Writes licensesignal/lib/signals.ts.  node src/build-signals.mjs
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { PATHS } from './config.mjs'

const out = (n) => fileURLToPath(new URL(n, PATHS.out))
const load = async (n) => {
  try {
    return JSON.parse(await readFile(out(n), 'utf8'))
  } catch {
    return []
  }
}
const APP_LIB = fileURLToPath(new URL('../../licensesignal/lib/signals.ts', import.meta.url))

function titleCase(s) {
  if (!s) return ''
  return String(s)
    .toLowerCase()
    .replace(/\b([a-z])/g, (_m, c) => c.toUpperCase())
    .replace(/\b(Llc|Inc|Lp|Llp|Pa)\b/g, (m) => m.toUpperCase())
}
const money = (n) => (n ? `$${Number(n).toLocaleString()}` : '')
const asOf = '2026-06-15'

function realAddr(r) {
  const a = r.address || {}
  return a.city && a.street && !/INACTIVE|NO /i.test(a.street)
}

// ── licenses (recent new liquor filings) ────────────────────────────────────
const licenses = (await load('normalized-abt_retail.json'))
  .filter((r) => r.eventType === 'new_filing' && realAddr(r))
  .slice(0, 40)
  .map((r) => ({
    id: r.id,
    signalType: 'license',
    businessName: titleCase(r.businessName),
    category: r._seriesLabel || 'Liquor license',
    detail: `New ${r._series || ''} liquor license filed`.replace('  ', ' '),
    city: titleCase(r.address.city),
    county: r.address.county === 'Dade' ? 'Miami-Dade' : r.address.county,
    date: r.filedDate || asOf,
    value: null,
    phone: null,
    sourceLabel: 'DBPR Alcoholic Beverages & Tobacco',
    lat: r.address.lat ?? null,
    lng: r.address.lng ?? null,
  }))

// ── new business registrations (Sunbiz) ──────────────────────────────────────
const registrations = (await load('sunbiz-new.json')).slice(0, 40).map((r) => ({
  id: r.id,
  signalType: 'registration',
  businessName: titleCase(r.businessName),
  category: `${r.entityType || 'New entity'}`,
  detail: 'New Florida business registered with the state',
  city: '',
  county: '',
  date: r.formedDate || asOf,
  value: null,
  phone: null,
  sourceLabel: 'FL Division of Corporations (Sunbiz)',
  lat: null,
  lng: null,
}))

// ── commercial building permits (Orlando) ────────────────────────────────────
const permits = (await load('normalized-permits-orlando.json')).slice(0, 30).map((r) => ({
  id: r.id,
  signalType: 'permit',
  businessName: titleCase(r.businessName),
  category: 'Commercial buildout',
  detail: [money(r.estimatedCost), r.permitCategory].filter(Boolean).join(' · ') || 'New commercial construction permit',
  city: titleCase(r.address.city),
  county: r.address.county,
  date: r.appliedDate || r.issuedDate || asOf,
  value: r.estimatedCost ?? null,
  phone: r.contractorPhone || null,
  sourceLabel: 'City of Orlando (building permits)',
  lat: null,
  lng: null,
}))

// ── retail food (FDACS, with phone) ──────────────────────────────────────────
const retail = (await load('normalized-fdacs.json'))
  .filter((r) => r.enrichment?.phone && realAddr(r))
  .slice(0, 40)
  .map((r) => ({
    id: r.id,
    signalType: 'retail_food',
    businessName: titleCase(r.businessName),
    category: r._category || 'Retail food',
    detail: `${r._category || 'Retail food'} establishment${r.enrichment.phone ? ' · ' + r.enrichment.phone : ''}`,
    city: titleCase(r.address.city),
    county: r.address.county,
    date: asOf,
    value: null,
    phone: r.enrichment.phone,
    sourceLabel: 'FDACS Division of Food Safety',
    lat: r.address.lat ?? null,
    lng: r.address.lng ?? null,
  }))

const all = [...licenses, ...registrations, ...permits, ...retail].sort((a, b) => (b.date || '').localeCompare(a.date || ''))

const counts = all.reduce((m, s) => ((m[s.signalType] = (m[s.signalType] || 0) + 1), m), {})

const ts =
  `// AUTO-GENERATED by data-pipeline/src/build-signals.mjs from LIVE Florida public\n` +
  `// records — DBPR liquor, FL Sunbiz registrations, City of Orlando permits, FDACS\n` +
  `// retail food. Sourced ${asOf}. Do not hand-edit. See data-pipeline/SOURCES.md.\n` +
  `import type { BusinessSignal } from './types'\n\n` +
  `export const SIGNAL_UNIVERSE = {\n` +
  `  licenseesTracked: 52061,\n  retailFoodTracked: 51885,\n  newBusinessesPerWorkday: 586,\n  permitFeed: 'live',\n} as const\n\n` +
  `export const BUSINESS_SIGNALS: BusinessSignal[] = ${JSON.stringify(all, null, 2)}\n`

await writeFile(APP_LIB, ts, 'utf8')
console.log(`✓ wrote ${all.length} unified signals → licensesignal/lib/signals.ts`)
console.log(`  by source: ${Object.entries(counts).map(([k, v]) => `${k} ${v}`).join(', ')}`)
console.log(`  sample: ${all.slice(0, 3).map((s) => `${s.businessName} [${s.signalType}]`).join(' | ')}`)
