// Fetch REAL Texas TABC license aggregates (the verified state #2 source) via the
// data.texas.gov Socrata API and emit licensesignal/lib/texas-stats.ts so the
// /expansion/texas page can show real numbers instead of placeholder copy.
//
//   node src/fetch-tabc.mjs
//
// Aggregate-only (count/group queries) — we don't download all ~125k rows, just the
// statewide total + per-county + per-type counts. Socrata sits behind Cloudflare,
// which 403s Node's fetch/undici, so we shell out to curl (same as the Orlando
// permits fetcher). Build the URL manually — URLSearchParams would percent-encode
// the leading `$` in Socrata params and break the query.
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const exec = promisify(execFile)
const BASE = 'https://data.texas.gov/resource/7hf9-qc9f.json'
const OUT = fileURLToPath(new URL('../../licensesignal/lib/texas-stats.ts', import.meta.url))
const asOf = '2026-06-15'

async function soda(query) {
  const url = `${BASE}?${query}`
  const { stdout } = await exec('curl', ['-s', '--max-time', '60', url], { maxBuffer: 64 * 1024 * 1024 })
  return JSON.parse(stdout)
}

const titleCase = (s) =>
  String(s || '')
    .toLowerCase()
    .replace(/\b([a-z])/g, (_m, c) => c.toUpperCase())

console.log('Fetching Texas TABC aggregates from data.texas.gov…')
const total = Number((await soda('$select=count(*)'))[0].count)

const countyRows = await soda(
  '$select=county,count(*)&$group=county&$order=count(*)%20desc&$limit=12'
)
const topCounties = countyRows
  .filter((r) => r.county && r.county.trim())
  .map((r) => ({ county: titleCase(r.county), count: Number(r.count) }))

const typeRows = await soda('$select=license_type,count(*)&$group=license_type&$limit=200')
const licenseTypeCount = typeRows.filter((r) => r.license_type).length

const banner = `// AUTO-GENERATED by data-pipeline/src/fetch-tabc.mjs from the Texas TABC public
// license file (data.texas.gov Socrata dataset 7hf9-qc9f, updated daily). Real
// statewide aggregates for the /expansion/texas preview. Sourced ${asOf}.
// Do not hand-edit — re-run the fetcher. See data-pipeline/SOURCES.md.
`
const ts =
  banner +
  `export interface TxCountyStat { county: string; count: number }\n\n` +
  `export const TX_DATA_AS_OF = '${asOf}'\n` +
  `export const TX_SOURCE = 'Texas Alcoholic Beverage Commission (TABC) — data.texas.gov'\n` +
  `export const TX_TOTAL_LICENSES = ${total}\n` +
  `export const TX_LICENSE_TYPE_COUNT = ${licenseTypeCount}\n` +
  `export const TX_TOP_COUNTIES: TxCountyStat[] = ${JSON.stringify(topCounties, null, 2)}\n`

await writeFile(OUT, ts, 'utf8')
console.log(`✓ wrote Texas stats → licensesignal/lib/texas-stats.ts`)
console.log(`  total TABC licenses: ${total.toLocaleString()}`)
console.log(`  license types: ${licenseTypeCount}`)
console.log(`  top counties: ${topCounties.slice(0, 5).map((c) => `${c.county} ${c.count}`).join(', ')}`)
